MagazzinoSmart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api/', include('api.urls')),
    path('', include('magazzino.urls')),
    path('admin/', admin.site.urls),
]

api/urls.py
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from api.CRUDViews.Acquisto import AcquistoCreate, AcquistoUpdate, AcquistoDestroy
from api.CRUDViews.Categoria import CategoriaDestroy, CategoriaUpdate, CategoriaCreate, CategoriaList
from api.CRUDViews.Fornitore import FornitoreDestroy, FornitoreUpdate, FornitoreCreate
from api.CRUDViews.Negozio import NegozioCreate, NegozioUpdate, NegozioDestroy, ProdottiInNegozio
from api.CRUDViews.Prodotto import ProdottoCreate, ProdottoUpdate, ProdottoDestroy, ProdottiFilteredGet
from api.CRUDViews.Vendita import VenditaCreate, VenditaUpdate, VenditaDestroy, TopSelledProdottiByFilter

app_name = 'api'

schema_view = get_schema_view(
   openapi.Info(
      title="CRUD API",
      default_version='v1',
      description="CRUD METHODS",
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path(r'negozio/create', NegozioCreate.as_view(), name="acquisto-create"),
    path(r'negozio/update/<int:pk>', NegozioUpdate.as_view(), name="negozio-update"),
    path(r'negozio/delete/<int:pk>', NegozioDestroy.as_view(), name="negozio-delete"),
    path(r'negozio/topsupplied', ProdottiInNegozio.as_view(), name="negozio-get-topsupplied"),


    path(r'prodotto/create', ProdottoCreate.as_view(), name="prodotto-create"),
    path(r'prodotto/update/<int:pk>', ProdottoUpdate.as_view(), name="prodotto-update"),
    path(r'prodotto/delete/<int:pk>', ProdottoDestroy.as_view(), name="prodotto-delete"),
    path(r'prodotto/get', ProdottiFilteredGet.as_view(), name='prodotto_get_by_negozio_di'),

    path(r'categoria/create', CategoriaCreate.as_view(), name="acquisto-create"),
    path(r'categoria/update/<int:pk>', CategoriaUpdate.as_view(), name="categoria-update"),
    path(r'categoria/delete/<int:pk>', CategoriaDestroy.as_view(), name="categoria-delete"),
    path(r'categoria/list', CategoriaList.as_view(), name="categoria-list"),

    path(r'fornitore/create', FornitoreCreate.as_view(), name="acquisto-create"),
    path(r'fornitore/update/<int:pk>', FornitoreUpdate.as_view(), name="fornitore-update"),
    path(r'fornitore/delete/<int:pk>', FornitoreDestroy.as_view(), name="fornitore-delete"),

    path(r'vendita/create', VenditaCreate.as_view(), name="vendita-create"),
    path(r'vendita/update/<int:pk>', VenditaUpdate.as_view(), name="vendita-update"),
    path(r'vendita/delete/<int:pk>', VenditaDestroy.as_view(), name="vendita-delete"),
    path(r'vendita/topselled', TopSelledProdottiByFilter.as_view(), name='topselled_products_by_filter'),

    path(r'acquisto/create', AcquistoCreate.as_view(), name="acquisto-create"),
    path(r'acquisto/update/<int:pk>', AcquistoUpdate.as_view(), name="acquisto-update"),
    path(r'acquisto/delete/<int:pk>', AcquistoDestroy.as_view(), name="acquisto-delete"),

    path(r'swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui')
]

magazzino/urls.py
from django.shortcuts import redirect
from django.urls import path
from magazzino import views

app_name = 'magazzino'

urlpatterns = [
    path('', lambda request: redirect('home/', permanent=False)),
    path('home/', views.home, name='home'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('prodotti/', views.ProdottiList.as_view(), name='prodotti'),
    path('prodotto/create', views.prodotto_create, name='nuovo-prodotto'),
]

magazzino/models.py
from django.contrib import auth
from django.db import models
from django.db.models import CASCADE

from magazzino.Service import DepositoService

'''
Per motivi di comodità non ho assegnato le chiavi primarie corrette ma ho utilizzato su ogni tabella il campo 'id' 
che viene inizializzato in automatico da django.

Questo sito è stato pensato per aiutare a supervisionare i prodotti del tuo negozio, trovare i prodotti di tendenza e 
semplificare la gestione del magazzino. Non è stato pensato per gestire la parte contabile del magazzino ma solo quella
logica per poter fare in base ai grafici degli interventi sull'efficienza dell'attività.
'''


class Negozio(models.Model):
    Nome = models.CharField(max_length=64)
    User = models.ForeignKey(auth.get_user_model(), on_delete=CASCADE)

    def __str__(self):
        return self.Nome

    class Meta:
        verbose_name_plural = 'Negozi'


class Prodotto(models.Model):
    Nome = models.CharField(max_length=64)
    UnitaDiMisura = models.CharField(max_length=16)

    def __str__(self):
        return self.Nome

    class Meta:
        verbose_name_plural = 'Prodotti'


class Categoria(models.Model):
    Nome = models.CharField(max_length=64)
    Descrizione = models.TextField(max_length=1024)

    def __str__(self):
        return self.Nome

    class Meta:
        verbose_name_plural = 'Categorie'


class Fornitore(models.Model):
    Nome = models.CharField(max_length=64)
    Descrizione = models.TextField(max_length=1024)

    def __str__(self):
        return self.Nome

    class Meta:
        verbose_name_plural = 'Fornitori'


class Deposito(models.Model):
    Negozio = models.ForeignKey(Negozio, on_delete=CASCADE)
    Prodotto = models.ForeignKey(Prodotto, on_delete=CASCADE)
    Quantita = models.FloatField()
    Descrizione = models.TextField(max_length=1024)

    def __str__(self):
        return self.Prodotto.Nome + ' ' + str(self.Quantita)

    class Meta:
        verbose_name_plural = 'Deposito (Prodotto -> Negozio)'


class Acquisto(models.Model):
    Negozio = models.ForeignKey(Negozio, on_delete=CASCADE)
    Fornitore = models.ForeignKey(Fornitore, on_delete=CASCADE, null=True, blank=True)
    Prodotto = models.ForeignKey(Prodotto, on_delete=CASCADE)
    Quantita = models.FloatField()
    DataA = models.DateTimeField()

    # Programmatically implemented SQL triggers
    previus_quantity = 0

    def __init__(self, *args, **kwargs):
        super(Acquisto, self).__init__(*args, **kwargs)

        # discrimino update e insert usando gli argomenti
        if kwargs.get('Quantita', False):
            self.previus_quantity = 0
        else:
            self.previus_quantity = self.Quantita

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.previus_quantity is None:
            self.previus_quantity = 0
        delta_quantity = self.previus_quantity - self.Quantita
        DepositoService.modify_deposit_product_supply(self.Prodotto, self.Negozio, delta_quantity * -1)

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        DepositoService.modify_deposit_product_supply(self.Prodotto, self.Negozio, self.Quantita * -1)

    def __str__(self):
        return self.Negozio.Nome + ' / ' + self.Fornitore.Nome + ' -> ' + str(self.Quantita) + str(self.Prodotto.UnitaDiMisura) + ' ' + self.Prodotto.Nome #sas

    class Meta:
        verbose_name_plural = 'Acquisti'


class Vendita(models.Model):
    Negozio = models.ForeignKey(Negozio, on_delete=CASCADE)
    Prodotto = models.ForeignKey(Prodotto, on_delete=CASCADE)
    Quantita = models.FloatField()
    DataV = models.DateTimeField()

    # Programmatically implemented SQL triggers
    previus_quantity = 0

    def __init__(self, *args, **kwargs):
        super(Vendita, self).__init__(*args, **kwargs)

        # discrimino update e insert usando gli argomenti
        if kwargs.get('Quantita', False):
            self.previus_quantity = 0
        else:
            self.previus_quantity = self.Quantita

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.previus_quantity is None:
            self.previus_quantity = 0
        delta_quantity = self.previus_quantity - self.Quantita
        DepositoService.modify_deposit_product_supply(self.Prodotto, self.Negozio, delta_quantity)
        self.previus_quantity = self.Quantita

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        DepositoService.modify_deposit_product_supply(self.Prodotto, self.Negozio, self.Quantita)

    def __str__(self):
        return self.Negozio.Nome + ' -> ' + str(self.Quantita) + str(self.Prodotto.UnitaDiMisura) + ' ' + self.Prodotto.Nome

    class Meta:
        verbose_name_plural = 'Vendite'


class Appartiene(models.Model):
    Negozio = models.ForeignKey(Negozio, on_delete=CASCADE)
    Prodotto = models.ForeignKey(Prodotto, on_delete=CASCADE)
    Categoria = models.ForeignKey(Categoria, on_delete=CASCADE)

    def __str__(self):
        return self.Prodotto.Nome + ' -> ' + self.Categoria.Nome

    class Meta:
        verbose_name_plural = 'Appartiene (Prodotto -> Categoria)'

magazzino/forms.py
from django.contrib.auth.models import User
from django.forms import forms, ModelForm, Form, DateInput

from magazzino.models import Acquisto, Vendita, Prodotto


class LoginForm(Form):
    class Meta:
        model = User
        fields = ('username', 'password')


class DateInput(DateInput):
    input_type = 'date'


class AcquistoForm(ModelForm):
    class Meta:
        model = Acquisto
        fields = ['Fornitore', 'Prodotto', 'Quantita']


class VenditaForm(ModelForm):
    class Meta:
        model = Vendita
        fields = ['Prodotto', 'Quantita']


class ProdottoForm(ModelForm):
    class Meta:
        model = Prodotto
        fields = ['Nome', 'UnitaDiMisura']

magazzino/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView

from magazzino import forms
from magazzino.forms import AcquistoForm, VenditaForm, ProdottoForm
from magazzino.models import Negozio, Deposito, Prodotto, Categoria


class LoginUser(LoginView):
    template_name = 'login.html'
    from_class = forms.LoginForm


@login_required
def logout_user(request):
    logout(request)
    return redirect('magazzino:home')


def home(request):
    data = {
        'acquistoFrom': AcquistoForm(),
        'venditaFrom': VenditaForm(),
        'categorie': Categoria.objects.all()
    }
    if request.user.is_authenticated:
        tempNegozio = Negozio.objects.filter(User=request.user).first()
        if tempNegozio is not None:
            data['Negozio'] = tempNegozio.id
        else:
            return HttpResponse('Unauthorized', status=401)

    return render(request, 'magazzino/index.html', data)


class ProdottiList(ListView):
    model = Deposito
    template_name = 'magazzino/prodotti.html'

    def get_queryset(self):
        filter_val = Negozio.objects.filter(User=self.request.user.id).first().id
        new_context = Deposito.objects.filter(
            Negozio_id=filter_val,
        )
        return new_context

    def get_context_data(self,**kwargs):
        context = super(ProdottiList,self).get_context_data(**kwargs)
        context['Negozio'] = Negozio.objects.filter(User=self.request.user).first().id
        return context


@login_required
def prodotto_create(request):
    template_name = 'magazzino/prodotto-create.html'
    data = {
        'form': ProdottoForm()
    }

    return render(request, 'magazzino/prodotto-create.html', data)

magazzino/templates/magazzino/prodotti.html
{% extends 'base.html' %}

{% block title %}Lista prodotti{% endblock %}

{% block content %}
    <div class="row">
        <div class="card">
            <div class="card-content">
                <div class="card-title">Lista dei prodotti</div>
                <table class="centered responsive-table">
                    <thead>
                        <th>Nome Prodotto</th>
                        <th>Quantita del prodotto</th>
                        <th>Descrizione</th>
                        <th>Operazioni</th>
                    </thead>
                    <tbody>
                        {% for deposito in object_list %}
                        <tr>
                            <td>{{ deposito.Prodotto.Nome }}</td>
                            <td id="quantita_{{ deposito.Prodotto.id }}">{{ deposito.Quantita }} {{ deposito.Prodotto.UnitaDiMisura }}</td>
                            <td>{{ deposito.Descrizione }}</td>
                            <td>
                                {% if deposito.Quantita < 0 %}
                                    <button class="waves-effect waves-light btn" onclick="acquistaProdotti(this, {{ deposito.Prodotto.id }}, '{{ deposito.Prodotto.Nome }}', {{ deposito.Quantita }})">Azzera</button>
                                {% elif deposito.Quantita > 0 %}
                                    <button class="waves-effect waves-light red btn" onclick="vendiProdotti(this, {{ deposito.Prodotto.id }}, '{{ deposito.Prodotto.Nome }}', {{ deposito.Quantita }})">Vendi Tutto</button>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="fixed-action-btn">
        <a href="{% url 'magazzino:nuovo-prodotto' %}" class="btn-floating btn-large green">
            <i class="large material-icons black-text">add</i>
        </a>
    </div>
{% endblock %}

{% block script %}
<script>
    function vendiProdotti(bottone, ProdottoId, ProdottoNome, Quantita){
        var data = {};

        data['Negozio'] = {{ Negozio }};
        data['Prodotto'] = ProdottoId;
        data['Quantita'] = Quantita;
        data['DataV'] = moment(new Date()).format('YYYY-MM-DD HH:mm');

        $.ajax({
            type: 'POST',
            contentType: "application/json",
            url: "{% url 'api:vendita-create' %}",
            headers: {
                "X-CSRFToken": '{{ csrf_token }}',
            },
            data: JSON.stringify(data),
            dataType: 'json'
        }).done(function(data) {
            M.toast({
                html: 'Vendita di ' + Quantita + ' x ' + ProdottoNome,
                classes: 'green-text'
            });

            $("#quantita_"+ProdottoId)[0].innerText = $("#quantita_"+ProdottoId)[0].innerText.replace(Quantita, "0");
            bottone.remove();
        });
    }

    function acquistaProdotti(bottone, ProdottoId, ProdottoNome, Quantita){
        var data = {};

        Quantita = Quantita * -1;

        data['Negozio'] = {{ Negozio }};
        data['Prodotto'] = ProdottoId;
        data['Quantita'] = Quantita;
        data['DataA'] = moment(new Date()).format('YYYY-MM-DD HH:mm');

        $.ajax({
            type: 'POST',
            contentType: "application/json",
            url: "{% url 'api:acquisto-create' %}",
            headers: {
                "X-CSRFToken": '{{ csrf_token }}',
            },
            data: JSON.stringify(data),
            dataType: 'json'
        }).done(function(data) {
            M.toast({
                html: 'Acquisto di ' + Quantita + ' x ' + ProdottoNome,
                classes: 'green-text'
            });

            $("#quantita_"+ProdottoId)[0].innerText = $("#quantita_"+ProdottoId)[0].innerText.replace(Quantita, "0");
            bottone.remove();
        });
    }
</script>

{% endblock %}

magazzino/templates/magazzino/prodotto-create.html
{% extends 'base.html' %}

{% block title %}Lista prodotti{% endblock %}

{% block content %}
    <div class="row">
        <div class="card">
            <div class="card-content">
                <div class="card-title">Lista dei prodotti</div>
                <form id="form-nuovo-prodotto" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn" type="button" onclick="aggiungiProdotto()">Aggiungi <i class="material-icons right">add</i></button>
                </form>
            </div>
        </div>
    </div>
    <div class="fixed-action-btn">
        <a href="{% url 'magazzino:nuovo-prodotto' %}" class="btn-floating btn-large green">
            <i class="large material-icons black-text">add</i>
        </a>
    </div>
{% endblock %}

{% block script %}
    <script>
        function aggiungiProdotto() {
            var isFormValid = $("#form-nuovo-prodotto")[0].checkValidity();

            if (isFormValid) {
                var data = serializeArrayToFormData($("#form-nuovo-prodotto").serializeArray());
                console.log(data);
                $.ajax({
                    type: 'POST',
                    contentType: "application/json",
                    url: "{% url 'api:prodotto-create' %}",
                    headers: {
                        "X-CSRFToken": document.getElementsByName('csrfmiddlewaretoken')[0].value,
                    },
                    data: JSON.stringify(data),
                    dataType: 'json'
                }).done(function(data) {
                    M.toast({
                        html: 'Prodotto inserito!',
                        classes: 'green-text'
                    });
                });

                $("#form-acquisto").find("input[type=text], textarea").val("");
            } else {
                M.toast({
                    html: 'Inserire tutti i valori!',
                    classes: 'red-text'
                });
            }
        }
    </script>
{% endblock %}