MagazzinoSmart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api/', include('api.urls')),
    path('', include('magazzino.urls')),
    path('admin/', admin.site.urls),
]

api/urls.py
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from api.CRUDViews.Acquisto import AcquistoCreate, AcquistoUpdate, AcquistoDestroy
from api.CRUDViews.Categoria import CategoriaDestroy, CategoriaUpdate, CategoriaCreate, CategoriaList
from api.CRUDViews.Fornitore import FornitoreDestroy, FornitoreUpdate, FornitoreCreate
from api.CRUDViews.Negozio import NegozioCreate, NegozioUpdate, NegozioDestroy, ProdottiInNegozio
from api.CRUDViews.Prodotto import ProdottoCreate, ProdottoUpdate, ProdottoDestroy, ProdottiFilteredGet
from api.CRUDViews.Vendita import VenditaCreate, VenditaUpdate, VenditaDestroy, TopSelledProdottiByFilter

app_name = 'api'

schema_view = get_schema_view(
   openapi.Info(
      title="CRUD API",
      default_version='v1',
      description="CRUD METHODS",
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path(r'negozio/create', NegozioCreate.as_view(), name="acquisto-create"),
    path(r'negozio/update/<int:pk>', NegozioUpdate.as_view(), name="negozio-update"),
    path(r'negozio/delete/<int:pk>', NegozioDestroy.as_view(), name="negozio-delete"),
    path(r'negozio/topsupplied', ProdottiInNegozio.as_view(), name="negozio-get-topsupplied"),


    path(r'prodotto/create', ProdottoCreate.as_view(), name="prodotto-create"),
    path(r'prodotto/update/<int:pk>', ProdottoUpdate.as_view(), name="prodotto-update"),
    path(r'prodotto/delete/<int:pk>', ProdottoDestroy.as_view(), name="prodotto-delete"),
    path(r'prodotto/get', ProdottiFilteredGet.as_view(), name='prodotto_get_by_negozio_di'),

    path(r'categoria/create', CategoriaCreate.as_view(), name="acquisto-create"),
    path(r'categoria/update/<int:pk>', CategoriaUpdate.as_view(), name="categoria-update"),
    path(r'categoria/delete/<int:pk>', CategoriaDestroy.as_view(), name="categoria-delete"),
    path(r'categoria/list', CategoriaList.as_view(), name="categoria-list"),

    path(r'fornitore/create', FornitoreCreate.as_view(), name="acquisto-create"),
    path(r'fornitore/update/<int:pk>', FornitoreUpdate.as_view(), name="fornitore-update"),
    path(r'fornitore/delete/<int:pk>', FornitoreDestroy.as_view(), name="fornitore-delete"),

    path(r'vendita/create', VenditaCreate.as_view(), name="vendita-create"),
    path(r'vendita/update/<int:pk>', VenditaUpdate.as_view(), name="vendita-update"),
    path(r'vendita/delete/<int:pk>', VenditaDestroy.as_view(), name="vendita-delete"),
    path(r'vendita/topselled', TopSelledProdottiByFilter.as_view(), name='topselled_products_by_filter'),

    path(r'acquisto/create', AcquistoCreate.as_view(), name="acquisto-create"),
    path(r'acquisto/update/<int:pk>', AcquistoUpdate.as_view(), name="acquisto-update"),
    path(r'acquisto/delete/<int:pk>', AcquistoDestroy.as_view(), name="acquisto-delete"),

    path(r'swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui')
]

magazzino/urls.py
from django.shortcuts import redirect
from django.urls import path
from magazzino import views

app_name = 'magazzino'

urlpatterns = [
    path('', lambda request: redirect('home/', permanent=False)),
    path('home/', views.home, name='home'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('prodotti/', views.ProdottiList.as_view(), name='prodotti'),
    path('prodotto/create', views.prodotto_create, name='nuovo-prodotto'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <script type="text/javascript" src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js" integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ==" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

    <!--Import Google Font And Icons-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <!--<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">-->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.css' %}" media="screen,projection"/>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <script>
        $(document).ready(function() {
            $('.dropdown-trigger').dropdown({
                coverTrigger: false,
                constrainWidth: false
            });
        });
    </script>
    {% block script %}{% endblock %}
    <ul id="menu-utente" class="dropdown-content">
        {% if user.is_authenticated %}
            <li><a href="{% url 'magazzino:logout' %}" class="red-text text-accent-4">Logout</a></li>
        {% endif %}
    </ul>
    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <a href="{% url 'magazzino:home' %}" class="brand-logo">
                    <img class="circle glass-circle responsive-img" src="{% static 'img/MagazzinoSmart.png' %}" alt="Logo" style="width: 48px; height: 48px; margin-top: 8px; margin-left: 8px;">
                </a>
                <a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <ul class="right">
                    {% if user.is_authenticated %}
                        <li class="hide-on-med-and-down"><a href="{% url 'magazzino:prodotti' %}">Prodotti</a></li>
                        <li class="hide-on-med-and-down"><a href="#">Impostazioni</a></li>
                        <li><a class="dropdown-trigger" href="#!" data-target="menu-utente">{{ user.username }}</a></li>
                    {% else %}
                        <li><a href="{% url 'magazzino:login' %}">Login</a></li>
                    {% endif %}
                </ul>
                <ul class="sidenav" id="mobile-nav">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'magazzino:prodotti' %}">Prodotti</a></li>
                        <li><a href="#">Impostazioni</a></li>
                    {% else %}
                        <li><a href="{% url 'magazzino:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!--JavaScript at end of body for optimized loading-->
    <script !src="">
        $(document).ready( function() {
            M.AutoInit();
        });

        function serializeArrayToFormData(arr) {
            var data = {};
            for (let i = 0; i<arr.length; i++) {
                var input = arr[i];
                data[input.name] = input.value;
            }
            return data;
        }
    </script>
    <script type="text/javascript" src="{% static 'js/materialize/bin/materialize.js' %}"></script>
</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}
    <div class="row center">
        <div class="col xl8 offset-xl2 l10 offset-l1 m12 s12">
            <div class="hoverable card z-depth-2">
                <form id="login-form" method="POST">
                    <div class="card-content">
                        <span class="card-title">Login</span>
                            {% csrf_token %}
                            {% for field in form.visible_fields %}
                                <div class="input-field">
                                    {{ field }}
                                    <label for="{{ field.label }}">{{ field.label }}</label>
                                </div>
                            {% endfor %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    </div>
                    <div class="card-action">
                        <div class="row valign-wrapper" style="margin-bottom: 0px !important;">
                            <div class="col s6 m3 xl4 center-align">
                                <a class="error-btn btn waves-effect waves-red" href="{% url 'magazzino:home' %}">Annulla</a>
                            </div>
                            <div class="col s6 m3 offset-m6 xl4 offset-xl4  center-align">
                                <button class="center waves-effect waves-light btn" type="submit">Login <i class="material-icons right">login</i></button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}